# Generated by Django 5.0.4 on 2024-04-22 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_dadosmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedico',
            name='especialidades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medico.especialidades'),
        ),
    ]
