# Generated by Django 5.0.4 on 2024-04-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_dadosmedico_especialidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='CRM',
            new_name='crm',
        ),
    ]
