# Generated by Django 5.0.4 on 2024-04-22 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_rename_crm_dadosmedico_crm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosmedico',
            old_name='cedulas_identidade_medica',
            new_name='cedula_identidade_medica',
        ),
        migrations.RemoveField(
            model_name='dadosmedico',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='dadosmedico',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medico.especialidades'),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadosmedico',
            name='rua',
            field=models.CharField(max_length=100),
        ),
    ]
